/*
 * JS for screen4 generated by Exadel Tiggzi
 *
 * Created on: Saturday, May 05, 2012, 06:25:53 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle"; /* Object & array with components "name-to-id" mapping */
var n2id_buf = {
    'mobilelabel12': 'j_13',
    'mobileimage4': 'j_14',
    'mobilelabel7': 'j_15',
    'mobilelabel13': 'j_16',
    'mobilelabel10': 'j_17',
    'mobiletextarea4': 'j_18',
    'mobilebutton3': 'j_19'
};
if ("n2id" in window && n2id != undefined) {
    $.extend(n2id, n2id_buf);
} else {
    var n2id = n2id_buf;
}

function pageItem(pageName, pageLocation) {
    this.name = pageName;
    this.location = pageLocation;
}
Tiggr.AppPages = [
new pageItem('choosedoc1', 'screen-A28A.html'), new pageItem('choosedoc2', 'screen-EABD.html'), new pageItem('screen1', 'screen-0C6D.html'), new pageItem('screen2', 'screen-6E3F.html'), new pageItem('screen3', 'screen-800B.html'), new pageItem('screen4', 'screen-EC2C.html'), new pageItem('screen5', 'screen-F43B.html'), new pageItem('current', 'screen-EC2C.html')];
Tiggr.CurrentScreen = 'j_9';

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function unwrapAndApply(selector, content) {
    Tiggr.unwrapAndApply(selector, content);
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*************************
 *      SERVICES          *
 *************************/
var GetFBToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var GetFBData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
/*************************
 * NONVISUAL COMPONENTS  *
 *************************/
var datasources = [];
/************************
 * EVENTS AND HANDLERS  *
 ************************/
// screen onload
screen_EC2C_onLoad = j_9_onLoad = function() {
    createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
    Tiggr.__registerComponent('mobilelabel12', new Tiggr.BaseComponent({
        id: 'mobilelabel12',
        context: '#j_12'
    }));
    Tiggr.__registerComponent('mobileimage4', new Tiggr.BaseComponent({
        id: 'mobileimage4',
        context: '#j_12'
    }));
    Tiggr.__registerComponent('mobilelabel7', new Tiggr.BaseComponent({
        id: 'mobilelabel7',
        context: '#j_12'
    }));
    Tiggr.__registerComponent('mobilelabel13', new Tiggr.BaseComponent({
        id: 'mobilelabel13',
        context: '#j_12'
    }));
    Tiggr.__registerComponent('mobilelabel10', new Tiggr.BaseComponent({
        id: 'mobilelabel10',
        context: '#j_12'
    }));
    Tiggr.__registerComponent('mobiletextarea4', new Tiggr.BaseComponent({
        id: 'mobiletextarea4',
        context: '#j_12'
    }));
    Tiggr.__registerComponent('mobilebutton3', new Tiggr.BaseComponent({
        id: 'mobilebutton3',
        context: '#j_12'
    }));
    for (var idx = 0; idx < datasources.length; idx++) {
        datasources[idx].__setupDisplay();
    }
    screen_EC2C_elementsExtraJS();
    j_9_windowEvents();
    screen_EC2C_elementsEvents();
}
// screen window events
screen_EC2C_windowEvents = j_9_windowEvents = function() {
    $('#j_9').bind('pageshow orientationchange', function() {
        adjustContentHeightWithPadding();
    });
}
// screen elements extra js
screen_EC2C_elementsExtraJS = j_9_elementsExtraJS = function() {
    // screen (screen-EC2C) extra code
}
// screen elements handler
screen_EC2C_elementsEvents = j_9_elementsEvents = function() {
    $("a :input,a a,a fieldset label").live({
        click: function(event) {
            event.stopPropagation();
        }
    });
    $('#j_12 [name="mobilebutton3"]').die().live({
        vclick: function() {
            if (!$(this).attr('disabled')) {
                Tiggr.navigateTo('screen5', {
                    reverse: false
                });
            }
        },
    });
}
$("body").undelegate("pagebeforeshow").delegate("#j_9", "pagebeforeshow", function(event, ui) {
    j_9_onLoad();
});