/*
 * JS for screen5 generated by Exadel Tiggzi
 *
 * Created on: Saturday, May 05, 2012, 06:56:16 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle"; /* Object & array with components "name-to-id" mapping */
var n2id_buf = {
    'mobilelabel15': 'j_55',
    'mobilelabel16': 'j_56',
    'mobilelabel17': 'j_57',
    'mobilelabel18': 'j_58',
    'mobilelabel19': 'j_59',
    'mobilelabel20': 'j_60',
    'mobilebutton4': 'j_61'
};
if ("n2id" in window && n2id != undefined) {
    $.extend(n2id, n2id_buf);
} else {
    var n2id = n2id_buf;
}

function pageItem(pageName, pageLocation) {
    this.name = pageName;
    this.location = pageLocation;
}
Tiggr.AppPages = [
new pageItem('choosedoc2', 'screen-EABD.html'), new pageItem('screen1', 'screen-0C6D.html'), new pageItem('screen2', 'screen-6E3F.html'), new pageItem('screen3', 'screen-800B.html'), new pageItem('screen4', 'screen-EC2C.html'), new pageItem('screen5', 'screen-F43B.html'), new pageItem('screen6', 'screen-E014.html'), new pageItem('screen7', 'screen-A28A.html'), new pageItem('screen8_FBoutput', 'screen-4F9F.html'), new pageItem('current', 'screen-F43B.html')];
Tiggr.CurrentScreen = 'j_51';

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function unwrapAndApply(selector, content) {
    Tiggr.unwrapAndApply(selector, content);
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*************************
 *      SERVICES          *
 *************************/
var GetFBToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var GetFBData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/search',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
/*************************
 * NONVISUAL COMPONENTS  *
 *************************/
var datasources = [];
/************************
 * EVENTS AND HANDLERS  *
 ************************/
// screen onload
screen_F43B_onLoad = j_51_onLoad = function() {
    createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
    Tiggr.__registerComponent('mobilelabel15', new Tiggr.BaseComponent({
        id: 'mobilelabel15',
        context: '#j_54'
    }));
    Tiggr.__registerComponent('mobilelabel16', new Tiggr.BaseComponent({
        id: 'mobilelabel16',
        context: '#j_54'
    }));
    Tiggr.__registerComponent('mobilelabel17', new Tiggr.BaseComponent({
        id: 'mobilelabel17',
        context: '#j_54'
    }));
    Tiggr.__registerComponent('mobilelabel18', new Tiggr.BaseComponent({
        id: 'mobilelabel18',
        context: '#j_54'
    }));
    Tiggr.__registerComponent('mobilelabel19', new Tiggr.BaseComponent({
        id: 'mobilelabel19',
        context: '#j_54'
    }));
    Tiggr.__registerComponent('mobilelabel20', new Tiggr.BaseComponent({
        id: 'mobilelabel20',
        context: '#j_54'
    }));
    Tiggr.__registerComponent('mobilebutton4', new Tiggr.BaseComponent({
        id: 'mobilebutton4',
        context: '#j_54'
    }));
    for (var idx = 0; idx < datasources.length; idx++) {
        datasources[idx].__setupDisplay();
    }
    screen_F43B_elementsExtraJS();
    j_51_windowEvents();
    screen_F43B_elementsEvents();
}
// screen window events
screen_F43B_windowEvents = j_51_windowEvents = function() {
    $('#j_51').bind('pageshow orientationchange', function() {
        adjustContentHeightWithPadding();
    });
}
// screen elements extra js
screen_F43B_elementsExtraJS = j_51_elementsExtraJS = function() {
    // screen (screen-F43B) extra code
}
// screen elements handler
screen_F43B_elementsEvents = j_51_elementsEvents = function() {
    $("a :input,a a,a fieldset label").live({
        click: function(event) {
            event.stopPropagation();
        }
    });
    $('#j_54 [name="mobilebutton4"]').die().live({
        vclick: function() {
            if (!$(this).attr('disabled')) {
                Tiggr.navigateTo('screen7', {
                    reverse: false
                });
            }
        },
        vclick: function() {
            if (!$(this).attr('disabled')) {
                Tiggr.navigateTo('screen7', {
                    reverse: false
                });
            }
        },
    });
}
$("body").undelegate("pagebeforeshow").delegate("#j_51", "pagebeforeshow", function(event, ui) {
    j_51_onLoad();
});