/*
 * JS for screen6 generated by Exadel Tiggzi
 *
 * Created on: Saturday, May 05, 2012, 06:56:16 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle"; /* Object & array with components "name-to-id" mapping */
var n2id_buf = {
    'mobilepanel4': 'j_32',
    'mobileimage3': 'j_33',
    'mobilebutton3': 'j_34'
};
if ("n2id" in window && n2id != undefined) {
    $.extend(n2id, n2id_buf);
} else {
    var n2id = n2id_buf;
}

function pageItem(pageName, pageLocation) {
    this.name = pageName;
    this.location = pageLocation;
}
Tiggr.AppPages = [
new pageItem('choosedoc2', 'screen-EABD.html'), new pageItem('screen1', 'screen-0C6D.html'), new pageItem('screen2', 'screen-6E3F.html'), new pageItem('screen3', 'screen-800B.html'), new pageItem('screen4', 'screen-EC2C.html'), new pageItem('screen5', 'screen-F43B.html'), new pageItem('screen6', 'screen-E014.html'), new pageItem('screen7', 'screen-A28A.html'), new pageItem('screen8_FBoutput', 'screen-4F9F.html'), new pageItem('current', 'screen-E014.html')];
Tiggr.CurrentScreen = 'j_28';

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function unwrapAndApply(selector, content) {
    Tiggr.unwrapAndApply(selector, content);
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*************************
 *      SERVICES          *
 *************************/
var GetFBToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var GetFBData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/search',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
/*************************
 * NONVISUAL COMPONENTS  *
 *************************/
var datasources = [];
/************************
 * EVENTS AND HANDLERS  *
 ************************/
// screen onload
screen_E014_onLoad = j_28_onLoad = function() {
    createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
    Tiggr.__registerComponent('mobilepanel4', new Tiggr.BaseComponent({
        id: 'mobilepanel4',
        context: '#j_31'
    }));
    Tiggr.__registerComponent('mobileimage3', new Tiggr.BaseComponent({
        id: 'mobileimage3',
        context: '#j_31'
    }));
    Tiggr.__registerComponent('mobilebutton3', new Tiggr.BaseComponent({
        id: 'mobilebutton3',
        context: '#j_31'
    }));
    for (var idx = 0; idx < datasources.length; idx++) {
        datasources[idx].__setupDisplay();
    }
    screen_E014_elementsExtraJS();
    j_28_windowEvents();
    screen_E014_elementsEvents();
}
// screen window events
screen_E014_windowEvents = j_28_windowEvents = function() {
    $('#j_28').bind('pageshow orientationchange', function() {
        adjustContentHeightWithPadding();
    });
}
// screen elements extra js
screen_E014_elementsExtraJS = j_28_elementsExtraJS = function() {
    // screen (screen-E014) extra code
}
// screen elements handler
screen_E014_elementsEvents = j_28_elementsEvents = function() {
    $("a :input,a a,a fieldset label").live({
        click: function(event) {
            event.stopPropagation();
        }
    });
    $('#j_31 [name="mobilebutton3"]').die().live({
        vclick: function() {
            if (!$(this).attr('disabled')) {
                window.top.location = 'https://mhealth.att.com/mobile/auth?client_id=online_doctor&response_type=code&redirect_uri=http://www.mdease.com/auth.php&scope=%2Fread%2Fhealth%2Fuser%20%2Fread%2Fhealth%2Fdata%2Fmyzeo%20%2Fread%2Fhealth%2Fdata%2Ffitbit%20%2Fread%2Fhealth%2Fdata%2Fwithi';
            }
        },
    });
}
$("body").undelegate("pagebeforeshow").delegate("#j_28", "pagebeforeshow", function(event, ui) {
    j_28_onLoad();
});