/*
 * JS for choosedoc1 generated by Exadel Tiggzi
 *
 * Created on: Saturday, May 05, 2012, 06:25:53 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle"; /* Object & array with components "name-to-id" mapping */
var n2id_buf = {
    'mobilebutton2': 'j_62'
};
if ("n2id" in window && n2id != undefined) {
    $.extend(n2id, n2id_buf);
} else {
    var n2id = n2id_buf;
}

function pageItem(pageName, pageLocation) {
    this.name = pageName;
    this.location = pageLocation;
}
Tiggr.AppPages = [
new pageItem('choosedoc1', 'screen-A28A.html'), new pageItem('choosedoc2', 'screen-EABD.html'), new pageItem('screen1', 'screen-0C6D.html'), new pageItem('screen2', 'screen-6E3F.html'), new pageItem('screen3', 'screen-800B.html'), new pageItem('screen4', 'screen-EC2C.html'), new pageItem('screen5', 'screen-F43B.html'), new pageItem('current', 'screen-A28A.html')];
Tiggr.CurrentScreen = 'j_58';

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function unwrapAndApply(selector, content) {
    Tiggr.unwrapAndApply(selector, content);
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*************************
 *      SERVICES          *
 *************************/
var GetFBToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var GetFBData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': '',
    'dataType': 'json',
    'type': 'get',
});
/*************************
 * NONVISUAL COMPONENTS  *
 *************************/
var datasources = [];
/************************
 * EVENTS AND HANDLERS  *
 ************************/
// screen onload
screen_A28A_onLoad = j_58_onLoad = function() {
    createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
    Tiggr.__registerComponent('mobilebutton2', new Tiggr.BaseComponent({
        id: 'mobilebutton2',
        context: '#j_61'
    }));
    for (var idx = 0; idx < datasources.length; idx++) {
        datasources[idx].__setupDisplay();
    }
    screen_A28A_elementsExtraJS();
    j_58_windowEvents();
    screen_A28A_elementsEvents();
}
// screen window events
screen_A28A_windowEvents = j_58_windowEvents = function() {
    $('#j_58').bind('pageshow orientationchange', function() {
        adjustContentHeightWithPadding();
    });
}
// screen elements extra js
screen_A28A_elementsExtraJS = j_58_elementsExtraJS = function() {
    // screen (screen-A28A) extra code
}
// screen elements handler
screen_A28A_elementsEvents = j_58_elementsEvents = function() {
    $("a :input,a a,a fieldset label").live({
        click: function(event) {
            event.stopPropagation();
        }
    });
    $('#j_61 [name="mobilebutton2"]').die().live({
        vclick: function() {
            if (!$(this).attr('disabled')) {
                var url = 'https://m.facebook.com/dialog/oauth?client_id=420810684609850&redirect_uri=http://tiggzi.com/view/ddcb3d85-9fe3-43c3-8d51-3640efb89938/mob-screen-EABD.html&scope=user_education_history,friends_education_history,user_work_history,friends_work_history&state=' + OAuth.nonce(17);
                window.open(url);
            }
        },
    });
}
$("body").undelegate("pagebeforeshow").delegate("#j_58", "pagebeforeshow", function(event, ui) {
    j_58_onLoad();
});